name: Fuzz Parser

on:
  push:
    paths:
      - src/scanner.c
  pull_request:
    paths:
      - src/scanner.c
  workflow_dispatch:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: haml
          external-scanner: src/scanner.c
          time: 60
